[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build && cd ../backend && npm install"

[deploy]
startCommand = "cd backend && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
